######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 15 23:31:45 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
