######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 21 00:14:03 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += standarddialogs.h
SOURCES += main.cpp standarddialogs.cpp
