######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 25 02:23:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += standarddialogs.h
SOURCES += main.cpp standarddialogs.cpp
RESOURCES += test_pic.qrc
