######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 20 05:59:08 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += standarddialogs.h
SOURCES += main.cpp standarddialogs.cpp
